In [1]:
import numpy.linalg as la 
import numpy as np
la.norm(np.ones(4)) # Norm sqrt(x1^2+x2^2+...) also works for matrix 

2.0

In [2]:
la.norm([3,4])

5.0

In [3]:
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
la.norm(A)

16.881943016134134

In [4]:
la.det(A) # Determinant 

6.66133814775094e-16

In [5]:
la.matrix_rank(A) #Rank of matrix

2

In [6]:
la.matrix_power(A,2)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [7]:
eiganvalue,eiganvactor =la.eig(A) # Eigon values and eigonvactors
la.eigvals(A) #Just eigan calues

array([ 1.61168440e+01, -1.11684397e+00, -1.30367773e-15])

In [8]:
print("Eiganvalue is",eiganvalue)
print("eiganvactors ",eiganvactor)

Eiganvalue is [ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
eiganvactors  [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [9]:
la.inv(A) # inverse of matrix

array([[-4.50359963e+15,  9.00719925e+15, -4.50359963e+15],
       [ 9.00719925e+15, -1.80143985e+16,  9.00719925e+15],
       [-4.50359963e+15,  9.00719925e+15, -4.50359963e+15]])

In [10]:
# solving linear eqn 

la.solve(A,[1,2,3])

array([-0.33333333,  0.66666667,  0.        ])

In [11]:
la.svd(A)

(array([[-0.21483724,  0.88723069,  0.40824829],
        [-0.52058739,  0.24964395, -0.81649658],
        [-0.82633754, -0.38794278,  0.40824829]]),
 array([1.68481034e+01, 1.06836951e+00, 4.41842475e-16]),
 array([[-0.47967118, -0.57236779, -0.66506441],
        [-0.77669099, -0.07568647,  0.62531805],
        [-0.40824829,  0.81649658, -0.40824829]]))

# Singular Value Decomposition 

IF system is inconsistant  then it gives best fit. (OLS)
IF system is consistant then it will give one of the solution. 

IF rank (A|b)=rank(A) Consistant 
if = min(m,n) then unique solution 

In [12]:
la.pinv(A) # Sudo inverse.  

array([[-6.38888889e-01, -1.66666667e-01,  3.05555556e-01],
       [-5.55555556e-02,  3.46944695e-17,  5.55555556e-02],
       [ 5.27777778e-01,  1.66666667e-01, -1.94444444e-01]])

# LU Decomposition 
A= LU 
IF rank(A)=r
then if first r rows are linearly independent than A will have LU decomposition 



# Gramm-Schmidth Orthogonaliztion 
u1=a1/||a1|| 
u2=[a2-(a2.a1^)a1^]/norm


In [13]:
np.linalg.lstsq(A,b) # A daggar b Solve linear algebra

NameError: name 'b' is not defined

In [1]:
import numpy as np 

A=np.array([[2,3,7],[1,1,5],[4,3,1]])
b=np.array([5,13,3]).T


AttributeError: 'numpy.ndarray' object has no attribute 'dim'

In [ ]:

if np.rank(A)==np.rank(np.append(A,b,axis=1)):
    if()

# Newton Raphson 
x1=x0-f(x0)/f'(x0) 


x_{n+1}=x_n-f(xn)/f'(xn)

f(x*)=0
f(x)=f(xn)+f'(xn)(x-xn)+f''(xn)(x-xn)^2/2
0=f(xn)+f'(xn)(x*-xn)+f''(xn)(x*-xn)^2/2   Dividing by f'(xn)

xn -f(xn)/f'(xn) -x*= f''(xn)(x*-xn)^2/2f'(xn)

order of convergence 
lim n-> \inf  (x_{n+1}-x*)/(x_n-x*)^p \in (0,inf)

tanh(x)

square free polynomial 
Multiplicity of roots be equal one 

In [17]:
import numpy as np 
x=2
while np. abs ((np.exp(x)-np.exp(-x))/(np.exp(x)+np.exp(-x)))>=1e-6:
    x=x-(np.exp(x)-np.exp(-x))*(np.exp(x)+np.exp(-x))/4 
    print([x,(np.exp(x)-np.exp(-x))/(np.exp(x)+np.exp(-x))])

[-11.644958598563877, -0.9999999998464155]
[3255536207.187715, nan]


/tmp/ipykernel_2882/3290775978.py:5: RuntimeWarning: overflow encountered in exp
  print([x,(np.exp(x)-np.exp(-x))/(np.exp(x)+np.exp(-x))])
/tmp/ipykernel_2882/3290775978.py:5: RuntimeWarning: invalid value encountered in scalar divide
  print([x,(np.exp(x)-np.exp(-x))/(np.exp(x)+np.exp(-x))])
/tmp/ipykernel_2882/3290775978.py:3: RuntimeWarning: overflow encountered in exp
  while np. abs ((np.exp(x)-np.exp(-x))/(np.exp(x)+np.exp(-x)))>=1e-6:
/tmp/ipykernel_2882/3290775978.py:3: RuntimeWarning: invalid value encountered in scalar divide
  while np. abs ((np.exp(x)-np.exp(-x))/(np.exp(x)+np.exp(-x)))>=1e-6:


In [82]:
import numpy as np 

A=np.array([[2,3,7],[1,1,5]])
b=np.array([5,13])


In [59]:
np.concatenate((A,b),axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [19]:
np.linalg.pinv(A)@b

array([-2.21621622, -7.41891892,  4.52702703])

In [23]:

rA=np.linalg.matrix_rank(A)
rAb=np.linalg.matrix_rank(np.append(A,b))
u,s,v=np.linalg.svd(A)

In [27]:
print("Infinite solution:",s, "+ one of the element of null space with basis") 
print(v.T[:,rA:])

Infinite snp.linalg.rank(A)olution: [9.38938885 0.91617521] + one of the element of null space with basis
[[-0.92998111]
 [ 0.34874292]
 [ 0.11624764]]


In [28]:
A=np.array([[2,3,7],[1,1,5],[4,3,1]])
np.linalg.eigvals(A)

array([ 8.89018428, -0.57323846, -4.31694582])

In [77]:

#A=np.array([[2,3,7],[1,1,5],[1,1,5]])

A=np.array([[2,3,7],[1,1,5],[4,3,1]])
e,ev=np.linalg.eig(A)
ev

array([[-0.72869727, -0.55610719, -0.49269814],
       [-0.43008143,  0.81814926, -0.54516661],
       [-0.53294489, -0.14620734,  0.6782639 ]])

In [70]:
A@ev[:,2]

array([-3.77475828e-15,  0.00000000e+00,  0.00000000e+00])

In [78]:
print(A, "is indefinite")
print(ev[:,e==max(e)],'is vactor such that xTAx>0', )
print(ev[:,e==min(e)],'is vactor such that xTAx<0')



[[2 3 7]
 [1 1 5]
 [4 3 1]] is indefinite
[[-0.72869727]
 [-0.43008143]
 [-0.53294489]] is vactor such that xTAx>0
[[-0.49269814]
 [-0.54516661]
 [ 0.6782639 ]] is vactor such that xTAx<0


In [80]:
(ev[:,e==min(e)]).T @A@ev[:,e==min(e)]

array([[-4.31694582]])

In [85]:

A=np.array([[2,3,7],[1,1,5],[4,3,1],[2,1,5]])
b=np.array([5,13,3,15]).reshape((4,1))
np.linalg.lstsq(A,b,rcond=None)

(array([[ 5.80887372],
        [-7.74061433],
        [ 2.49488055]]),
 array([8.84641638]),
 3,
 array([11.26554452,  4.12324429,  1.04228755]))

In [93]:
import numpy as np 

A=np.array([[2,3,7],[1,1,5],[1,2,2]])
z=np.zeros(A.shape)

for i in range(A.shape[1]):
    if A[:,i].dot(A[:,i])>0:
        z[:,i]=A[:,i]
        for j in range(i):
            if z[:,j].dot(z[:,j])>0:
                z[:,i]=z[:,i]- z[:,i].dot(z[:,j])*z[:,j]/(z[:,j].dot(z[:,j]))


z_norm=np.array([np.sqrt(z[:,i].dot(z[:,i]))for i in range(A.shape[1])])



In [94]:
z
print("Maximal set of linearly independent colums are \n", A[:,z_norm>0])


Maximal set of linearly independent colums are 
 [[2 3]
 [1 1]
 [1 2]]


In [107]:
z_norm=np.array([np.sqrt(z[:,i].dot(z[:,i]))for i in range(A.shape[1])])
z[:,z_norm>0]=z[:,z_norm>0]/z_norm[z_norm>0]

In [108]:

z

array([[ 0.81649658,  0.        ,  0.        ],
       [ 0.40824829, -0.70710678,  0.        ],
       [ 0.40824829,  0.70710678,  0.        ]])

In [109]:
for i in range(A.shape[1]):
    if A[:,i].dot(A[:,i])>0:
        z[:,i]=A[:,i]
        for j in range(i):
            if z[:,j].dot(z[:,j])>0:
                z[:,i]=z[:,i]- z[:,i].dot(z[:,j])*z[:,j]/(z[:,j].dot(z[:,j]))

z_norm=np.array([np.sqrt(z[:,i].dot(z[:,i])) for i in range(A.shape[1])])
z[:,z_norm>0]=z[:,z_norm>0]/z_norm[z_norm>0]
print("Maximal set of linearly independent colums are \n", A[:,z_norm>0])
print("Orthonormal basis for colum space of A is",z)


Maximal set of linearly independent colums are 
 [[2 3]
 [1 1]
 [1 2]]
Orthonormal basis for colum space of A is [[ 0.81649658  0.          0.        ]
 [ 0.40824829 -0.70710678  0.        ]
 [ 0.40824829  0.70710678  0.        ]]


In [7]:
import numpy as np 
A=np.array([[1,0],[0,0],[0,1]]) 
B=np.zeros((A.shape[0],A.shape[0]))
B

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
B[:,:A.shape[1]]=A
u,z,v=np.linalg.svd(A)
for i in range(A.shape[1],A.shape[0]):
    B[:,i]=u[:,i]
    for j in range(i):
        B[:,i]=B[:,i]-B[:,i].dot(B[:,j])*B[:,j]

print(B)

[[ 1.  0.  0.]
 [ 0.  0. -1.]
 [ 0.  1.  0.]]


In [12]:
import numpy as np
np.array([[1,2],[2,4]])[:,1:].shape

(2, 1)

In [19]:
A=np.array([[1,1],[2,2]])
def r(A):
    j=A[0,:].copy()
    A[0,:]=A[1,:]
    A[1,:]=j
    print(A, "from func")

In [20]:
print(A)
r(A)
print(A)

[[1 1]
 [2 2]]
[[2 2]
 [1 1]] from func
[[2 2]
 [1 1]]


In [4]:
import numpy as np
x=np.arange(5)
x[x>2]=0
x

array([0, 1, 2, 0, 0])