In [1]:
import numpy as np
n=int(input("enter the number of rows"))
m=int(input("enter the number of columns"))
A_input=input("enter the digits of matrix with spaces")
A = np.array(list(map(int, A_input.split()))).reshape(n, m)
print(A)
b_input=input("enter the digits of matrix with spaces")
b = np.array(list(map(int, b_input.split()))).reshape(n, 1)
print(b)


ValueError: invalid literal for int() with base 10: ''

In [ ]:
#Consider the system of linear equations of the form Ax = b. Given the
#matrix A (of size m × n) and the vector b (of length n), write a code that
#finds whether the system has a unique solution, infinite solutions, or no
#solutions. Furthermore, the code must compute the solution if it is unique,
#characterize the complete solution if there are infinitely many, and provide
#the best fit solution along with the squared error if there are no solutions.

import numpy as np

def check_solution(A, b):
    # Check if the number of equations (rows of A) is less than the number of variables (columns of A)
    if A.shape[0] < A.shape[1]:
        print("The system is underdetermined (infinite solutions).")
        return

    # Check if the number of equations is greater than the number of variables
    elif A.shape[0] > A.shape[1]:
        print("The system is overdetermined (no solution).")
        return

    # Check if the matrix A is singular (det(A) == 0)
    elif np.linalg.det(A) == 0:
        print("The system is inconsistent (no solution).")
        return

    # Perform LU decomposition
    P, L, U = np.linalg.lu(A)

    # Solve for y in Ly = Pb
    y = np.linalg.solve(L, np.dot(P, b))

    # Solve for x in Ux = y
    x = np.linalg.solve(U, y)

    print("The system has a unique solution:", x)

check_solution(A,b)

The system is underdetermined (infinite solutions).


In [ ]:
import numpy as np
n=int(input("enter the number of rows"))
m=int(input("enter the number of columns"))
A_input=input("enter the digits of matrix with spaces")
A = np.array(list(map(int, A_input.split()))).reshape(n, m)
print(A)

[[4 5 6]
 [5 0 7]
 [6 7 8]]


In [ ]:
#Write a code to determine whether a given square symmetric matrix A is
#positive (semi)definite, negative (semi)definite, or indefinite.
#Furthermore, the code should find an x such that x T Ax = 0 and a y such that y
#T Ay ̸= 0 if A is semidefinite; and should find an x such that xT Ax > 0 and a y
#such that y T Ay < 0 if A is indefinite.

import numpy as np

def definite_classification(A):
    # Check if A is symmetric
    if not np.array_equal(A, A.T):
        print("Matrix A is not symmetric.")
        return

    # Compute the eigenvalues
    eigenvalues = np.linalg.eigvals(A)

    # Check eigenvalues for definiteness
    if np.min(eigenvalues) > 0:
        print("Matrix A is positive definite.")
    elif np.min(eigenvalues) >= 0:
        print("Matrix A is positive semidefinite.")
    elif np.max(eigenvalues) < 0:
        print("Matrix A is negative definite.")
    elif np.max(eigenvalues) <= 0:
        print("Matrix A is negative semidefinite.")
    else:
        print("Matrix A is indefinite.")
    
    eigenvalues, eigenvectors = np.linalg.eigh(A)
    x_positive = eigenvectors[:, eigenvalues > 0]  # Eigenvectors corresponding to positive eigenvalues
    y_negative = eigenvectors[:, eigenvalues < 0]  # Eigenvectors corresponding to negative eigenvalues
    print("x for x^T * A * x > 0:", x_positive)
    print("y for y^T * A * y < 0:", y_negative)

definite_classification(A)

Matrix A is indefinite.
x for x^T * A * x > 0: [[-0.51928954]
 [-0.45697351]
 [-0.72215897]]
y for y^T * A * y < 0: [[ 0.26070731 -0.81386121]
 [-0.88945543  0.00665228]
 [ 0.37536747  0.58102124]]


In [ ]:
#Gram-Schmidt orthogonalization process.
import numpy as np

def gram_schmidt(matrix):
    orthogonal_columns = []

    for i in range(matrix.shape[1]):
        column = matrix[:, i]  # Get the current column

        # Perform Gram-Schmidt orthogonalization
        for j in range(len(orthogonal_columns)):
            projection = np.dot(column, orthogonal_columns[j]) / np.dot(orthogonal_columns[j], orthogonal_columns[j])
            column = projection * orthogonal_columns[j]

        # Check if the resulting column is linearly independent
        if not np.isclose(np.linalg.norm(column), 0):
            orthogonal_columns.append(column)

    return orthogonal_columns

In [ ]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
orthogonal_basis = gram_schmidt(matrix)

print("Orthogonal Basis:")
for column in orthogonal_basis:
    print(column)

Orthogonal Basis:
[1 4 7]
[1.18181818 4.72727273 8.27272727]
[1.36363636 5.45454545 9.54545455]


In [ ]:
#Consider that you are given a set of vectors a1, a2, . . . , al with ai ∈ R
#m, and another set of vectors b1, b2, . . . , bl with bi ∈ R n. Write a code to
#construct a matrix A such that Col(A) = span(a1, . . . , an) and Row(A) =
#span(b1, b2, . . . , bm). Your code must print “Not possible” if such a matrix
#cannot be constructed

import numpy as np

def construct_matrix(a, b):
    m = len(a[0])
    n = len(b[0])
    l = len(a)

    if m > n:
        print("Not possible")
        return

    # Create a zero matrix A with size (m + n) x (m + n)
    A = np.zeros((m + n, m + n))

    # Fill the top left section of A with the vectors a1, a2, ..., an
    for i in range(l):
        A[i][:m] = a[i]

    # Fill the bottom right section of A with the vectors b1, b2, ..., bm
    for i in range(l):
        A[i + m][m:] = b[i]

    return A

a = [[1, 2], [3, 4]]
b = [[5, 6], [7, 8]]

A = construct_matrix(a, b)
print(A)

[[1. 2. 0. 0.]
 [3. 4. 0. 0.]
 [0. 0. 5. 6.]
 [0. 0. 7. 8.]]


In [ ]:
import numpy as np

def compute_svd(matrix):
    U, s, V = np.linalg.svd(matrix)
    return U, s, V

def extract_columns_svd(A, m):
    # Perform SVD decomposition
    U, S, V = np.linalg.svd(A)
    
    # Extract the first m columns of U
    U_m = U[:, :m]
    
    return U_m


In [ ]:
import numpy as np

def construct_orthonormal_matrix(A):
    m, n = A.shape
    additional_vectors = []

    for i in range(m, n):
        vector = A[:, i]
        for j in range(i):
            projection = np.dot(vector, additional_vectors[j])
            vector -= projection * additional_vectors[j]
        vector /= np.linalg.norm(vector)
        additional_vectors.append(vector)

    B = np.zeros((m, m + n - m))
    B[:, :m] = A
    for i in range(n - m):
        B[:, m + i] = additional_vectors[i]
    return B


In [ ]:
A = np.array([[1, 0], [0, 1], [1, 1]])
B = construct_orthonormal_matrix(A)
print(B)

[[1. 0.]
 [0. 1.]
 [1. 1.]]


In [ ]:
np.dot(B.T, A)

array([[2., 1.],
       [1., 2.]])

In [ ]:
#Assume that you are given a matrix A = [a1, a2, . . . , am] where ai ∈ R
#n are n-length vectors. Consider m < n, and that A is an orthonormal matrix.
#Write a code to construct another (n−m) vectors am+1, am+2, . . . , an such
#that the matrix B = [a1, . . . , an] is still an orthonormal matrix
import numpy as np

def construct_additional_vectors(A):
    m, n = A.shape
    additional_vectors = []

    for i in range(m, n):
        vector = np.random.rand(n)  # Generate a random vector
        for j in range(i):
            projection = np.dot(vector, A[:, j])
            vector -= projection * A[:, j]
        norm = np.linalg.norm(vector)
        if norm > 0:
            vector /= norm
        additional_vectors.append(vector)

    return np.array(additional_vectors).T

def construct_orthonormal_matrix(A):
    m, n = A.shape

    additional_vectors = construct_additional_vectors(A)
    B = np.zeros((m, n))

    # Fill B with columns from A and additional_vectors
    B[:, :m] = A
    B[:, m:] = additional_vectors

    return B
A = np.array([[1, 0], [0, 1], [0, 0]])  # Example of an orthonormal matrix
B = construct_orthonormal_matrix(A)
print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)

Matrix A:
[[1 0]
 [0 1]
 [0 0]]

Matrix B:
[[1. 0.]
 [0. 1.]
 [0. 0.]]


In [2]:
#Write a code to decompose a given matrix into the product of a lower and
#upper triangular matrix using recursion.
import numpy as np

def lu_decomposition_recursive(matrix):
    if matrix.shape[0] != matrix.shape[1]:
        raise ValueError("Input matrix must be square for LU decomposition.")

    n = matrix.shape[0]

    if n == 1:
        return np.array([[1]]), matrix.copy()

    # Split the matrix into four submatrices
    half = n // 2
    A11 = matrix[:half, :half]
    A12 = matrix[:half, half:]
    A21 = matrix[half:, :half]
    A22 = matrix[half:, half:]

    # Recursively decompose the submatrices
    L11, U11 = lu_decomposition_recursive(A11)
    L22, U22 = lu_decomposition_recursive(A22)

    # Compute intermediate matrices
    L21 = np.linalg.solve(L11, A21)
    U12 = np.linalg.solve(U22, A12)

    # Concatenate the matrices to form L and U
    L = np.block([[L11, np.zeros((half, half))],
                  [L21, L22]])
    U = np.block([[U11, U12],
                  [np.zeros((half, half)), U22]])

    return L, U
A = np.array([[4, 3], [2, 1]])
L, U = lu_decomposition_recursive(A)

print("Original Matrix A:")
print(A)
print("\nLower Triangular Matrix L:")
print(L)
print("\nUpper Triangular Matrix U:")
print(U)

print(L@U)

Original Matrix A:
[[4 3]
 [2 1]]

Lower Triangular Matrix L:
[[1. 0.]
 [2. 1.]]

Upper Triangular Matrix U:
[[4. 3.]
 [0. 1.]]
[[4. 3.]
 [8. 7.]]


In [ ]:
import sys
if True:
    sys.exit()
    print("Hello")

Hello


: 