In [31]:
import scipy.optimize as spo 
import numpy as np
f=lambda x: 4*x[0]**2-2*x[0]*x[1]+x[1]**2

In [32]:
res=spo.minimize(f,np.array([1,1]),options={'gtol':1e-6})

In [33]:
res.x

array([-8.81500659e-09, -6.08892092e-09])

In [34]:
res=spo.minimize(f,np.array([1,1]),options={'gtol':1e-6 ,'disp':True})

Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 6
         Function evaluations: 21
         Gradient evaluations: 7


In [35]:
res.x

array([-8.81500659e-09, -6.08892092e-09])

In [36]:
lin=spo.LinearConstraint([[1,2],[3,-4]],[-np.inf,4],[1,np.inf])

In [37]:
cons=lambda x: [x[0]**2+x[1]**2,x[0]*np.log(x[1])+x[1]**3]
nlc=spo.NonlinearConstraint(cons,[1,-np.inf],[1,2])
bd=spo.Bounds([1,2],[5,3])

In [38]:
res=spo.minimize(f,np.array([2,2]),constraints=[lin,nlc],bounds=bd,options={'gtol': 1e-6,'disp':True})

Positive directional derivative for linesearch    (Exit mode 8)
            Current function value: 12.0
            Iterations: 5
            Function evaluations: 3
            Gradient evaluations: 1


/usr/lib/python3/dist-packages/scipy/optimize/_constraints.py:525: OptimizeWarning: Equality and inequality constraints are specified in the same element of the constraint list. For efficient use with this method, equality and inequality constraints should be specified in separate elements of the constraint list. 
  warn("Equality and inequality constraints are specified in the same "
/tmp/ipykernel_9117/4152139255.py:1: OptimizeWarning: Unknown solver options: gtol
  res=spo.minimize(f,np.array([2,2]),constraints=[lin,nlc],bounds=bd,options={'gtol': 1e-6,'disp':True})


In [39]:
import sympy as sm
x,y=sm.symbols("x,y",positive=True)
z=sm.nsolve([x*y-72,10*x+x*y-42*y],(x,y),(18,4)) 
z1=sm.nsolve([(21-x)*(10-y)**2-108,10*x+x*y-42*y],(x,y),(18,4))

In [40]:
import numpy as np
t=np.array([z[1]/z[0],1])

In [41]:
(np.array([21,10])-np.array(z).T).dot(t)

array([7.37200774845054], dtype=object)

In [42]:
z,z1

(Matrix([
 [14.1583783043385],
 [5.08532816769964]]),
 Matrix([
 [15.2137706571309],
 [ 5.6796984982065]]))

In [43]:
15,50/9

(15, 5.555555555555555)

In [44]:
f1=lambda x: (x[0]*x[1])**2

In [45]:
15+50*2.7/9

30.0

In [46]:
18+4*2.7

28.8

In [47]:
15, 50/9 

(15, 5.555555555555555)